# Generated by Django 4.0.6 on 2022-08-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdName', models.CharField(max_length=20)),
                ('AdEmail', models.CharField(max_length=20)),
                ('AdPass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuizID', models.IntegerField()),
                ('Ques', models.CharField(max_length=40)),
                ('Op1', models.CharField(max_length=20)),
                ('Op2', models.CharField(max_length=20)),
                ('Op3', models.CharField(max_length=20)),
                ('Op4', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UName', models.CharField(max_length=20)),
                ('UEmail', models.CharField(max_length=20)),
                ('UPass', models.CharField(max_length=20)),
                ('UDOB', models.CharField(max_length=20)),
            ],
        ),
    ]
