# Generated by Django 4.0.6 on 2022-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyQuiz', '0002_quiz_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='AdEmail',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='UEmail',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
