# Generated by Django 4.0.6 on 2022-09-02 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EasyQuiz', '0004_rename_ans_quiz_quizname_remove_quiz_op1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuizID', models.IntegerField()),
                ('QuizName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='Ans',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='Op1',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='Op2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='Op3',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='Op4',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='Ques',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
