# Generated by Django 4.0.6 on 2022-09-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyQuiz', '0006_alter_allquiz_quizid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Ques',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
