# Generated by Django 4.0.6 on 2022-09-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyQuiz', '0007_alter_quiz_ques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Ques',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
